accelerator: "gpu"
num_nodes: 1
check_val_every_n_epoch: 1
default_root_dir: ${hydra:runtime.cwd}/struct_token_bench_logs
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
devices: -1
gradient_clip_val: 1.0
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 20
max_epochs: null
max_steps: ${..max_steps} #get value via interpolation
num_sanity_val_steps: 0 #since we use zero-2d, better default
precision: 32-true
reload_dataloaders_every_n_epochs: 1 #fine for mmap arrow files
val_check_interval: 1.0 #leave null, will be set to occur 1 step before checkpointing
accumulate_grad_batches: 1
deterministic: true
fast_dev_run: false
